# Generated by Django 5.2.5 on 2025-09-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_alter_teacher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='student_id',
            field=models.CharField(),
        ),
    ]
