# Generated by Django 5.2.5 on 2025-09-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_alter_subjects_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='student_id',
            new_name='subjects_id',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='grades',
            field=models.CharField(max_length=3),
        ),
    ]
