# Generated by Django 5.2.5 on 2025-09-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0005_rename_student_id_subjects_subjects_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time_slot',
            field=models.CharField(max_length=100),
        ),
    ]
